name: TestLightsOut

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies to unit tests
        working-directory: ./LightsOut.Api.UnitTests
        run: dotnet restore
      - name: Unit Tests
        run: dotnet test --no-restore --verbosity normal
